services:
  server:
    image: ncr-controller-backend:latest
    env_file:
      - .env
    ports:
      - "${grpcport}:${grpcport}"
      - "${restport}:${restport}"
    environment:
      CONTROLLER_TIMEOUT: "${CONTROLLER_TIMEOUT}"
    networks:
      ncr-network:
        aliases:
          - server
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.0
    ports:
      - "${dbpublishport}:${dbport}"
    volumes:
      - ./_postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${dbpass}"
      POSTGRES_USER: "${dbuser}"
      POSTGRES_DB: "${dbname}"
    networks:
      ncr-network:
        aliases:
          - db
    healthcheck:
      test: "pg_isready -q -h db"
      interval: 3s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    ports:
      - 8081:8080

networks:
  ncr-network:
    driver: bridge